version: '3.7'

services:

  dind:
    build:
      context: .
      dockerfile: dind/Dockerfile
      target: dind

  apache:
    build:
      context: .
      dockerfile: apache/Dockerfile
      target: apache

  php:
    build:
      context: .
      dockerfile: php/Dockerfile
      target: php

  php-debug:
    build:
      context: .
      dockerfile: php-debug/Dockerfile
      target: php-debug